modal
aiqyyn1/IdealnoeSvidanie pull request #4
Opened 2022-09-20 09:31 UTC by aiqyyn1

2022-09-20 10:32 UTC, aidoha requested changes

2022-09-20 10:32 UTC, aidoha commented on json12/lol.json
> +}
Файл был создан и изменен. Можно посмотреть в `src/places-list.json`

2022-09-20 10:32 UTC, aidoha commented on lol.json
> +}
Зачем нам нужен этот файл?

2022-09-20 10:32 UTC, aidoha commented on src/App.css
> +} */
я думаю этот файл был удален раньше, поэтому он нам не нужен

2022-09-20 10:32 UTC, aidoha commented on src/App.js
> +export default App;
Я удалил этот файл раньше поскольку мы перешли на react-router-dom. То есть в src/index.js мы используем компонент Main который находится в src/routes/main/index.js. Можно в компоненте main вызвать эту welcome модалку.

2022-09-20 10:32 UTC, aidoha commented on src/components/Client.js
> +// }
зачем нам этот файл?

2022-09-20 10:32 UTC, aidoha commented on src/components/Client.css
> +}
зачем нам этот файл? Более того, мы будем работать с `material ui` поэтому нам не потребуется использовать css файлы, а также `className`

2022-09-20 10:32 UTC, aidoha commented on src/components/modals/welcome/Modal.js
> +}
зачем нам такой же файл если уже существует такой же? src/components/modals/welcome/index.js

2022-09-20 10:32 UTC, aidoha commented on src/components/modals/welcome/index.js
> +export default function index() {
вместо `export default function index()` просто `export default function()`

2022-09-20 10:32 UTC, aidoha commented on src/components/modals/welcome/index.js
> +  const ref = useRef();
почему решил сделать через `useRerf()`

2022-09-20 10:32 UTC, aidoha commented on src/components/modals/welcome/modal.css
> +}
Так как мы работаем с `material ui` css файлы не будем использовать. Вместо `div` можно использовать https://mui.com/material-ui/react-box/. Также можно использовать существующий компонент https://mui.com/material-ui/react-dialog/

2022-09-20 10:32 UTC, aidoha commented on src/routes/main/index.js
> +	const [modalFalse, setModalFalse] =useState(false);
Название стейта стоит изменить. Например: `isOpenWelcomeModal`

2022-09-20 10:32 UTC, aidoha commented on src/routes/main/index.js
> +const t=()=>{
название функции стоит изменить. Наименование компонентов, функций, стейтов, переменных должны быть максимально понятными.

2022-09-20 11:37 UTC, aiqyyn1 commented on src/components/modals/welcome/index.js
> +export default function index() {
ок

2022-09-20 11:41 UTC, aiqyyn1 commented on src/components/modals/welcome/index.js
> +  const ref = useRef();
я фокус направил на  снажури модалки что бы когда оно  кликалась ,  модалка  off

2022-09-20 11:41 UTC, aiqyyn1 commented on src/components/modals/welcome/modal.css
> +}
ok

2022-10-02 07:37 UTC, closed without merging

2022-10-02 07:37 UTC, aidoha commented
Due to creating new PR